[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-wasm = "=0.2.0"

bevy_webgl2 = "0.5"
bevy = { version = "0.5", default-features = false, features = ["bevy_gltf", "bevy_winit", "render", "png"] }

[profile.release]
lto = true
opt-level = 's'
